services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/development/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/common/php-fpm/Dockerfile
    volumes:
      - ./:/var/www

  workspace:
    build:
      context: .
      dockerfile: docker/development/workspace/Dockerfile
    volumes:
      - ./:/var/www
    tty: true
    stdin_open: true

  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data-development:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  postgres-data-development:

networks:
  default:
